"""Generated by internal/protocol/gen from internal/protocol/protocol.json. DO NOT EDIT."""

# One marker file per in-flight speak, present for the whole synth+playback
# window. Polled by the menu bar app's speaking indicator and scanned by
# every stop path.
ACTIVITY_DIR = "/tmp/ava-tts-active"

# Overrides activity_dir. Its only real use is pointing tests at an isolated
# directory, so they do not touch the real one or any speak in flight. The
# TTSCONTROL_ prefix is kept from when one package was its only reader: it is
# a published escape hatch, and renaming it would silently stop working for
# anyone who set it.
ACTIVITY_DIR_ENV = "TTSCONTROL_ACTIVITY_DIR"

# Written by the start script, removed by the server's own idle exit. These
# disagreed once, so the idle exit cleaned up a file nothing created and left
# the real one behind.
ENGINE_PID_FILE = "/tmp/mlx-engine-server.pid"

# Where mlx-engine binds. Whoever holds a stale copy either fails to bind or
# health-checks a socket nobody is listening on, and then reports the engine
# down while it is running.
ENGINE_URL = "http://127.0.0.1:8765"

# Sidecar naming the playing process, for a stop to signal.
PLAY_PID_SUFFIX = ".play.pid"

# Exclusive flock(2) held for the duration of playback, so concurrent speaks
# (the MCP server, hooks, the menu bar) queue instead of talking over each
# other. Two paths would be two locks, and both would play at once.
PLAYBACK_LOCK = "/tmp/ava-tts-playback.lock"

# Overrides playback_lock, for the same reason activity_dir_env exists: a
# test that runs a real speak takes this lock, and on the shared path it
# queues behind any speech in flight on the machine. Every reader honours
# both or neither, or an isolated test is only half isolated.
PLAYBACK_LOCK_ENV = "AVA_PLAYBACK_LOCK"

# Sidecar telling a speak a stop was deliberate, so it neither plays nor
# treats the cancellation as a failure and falls back to `say`.
STOPPED_SUFFIX = ".stopped"

# Sidecar naming the synthesizing process, for a stop to signal.
SYNTH_PID_SUFFIX = ".synth.pid"

# Where ava puts what it produces: per-dictation audio, cleaned up on exit,
# and `ava monitor` transcript logs, which are kept.
TEMP_DIR = "/tmp/voice-input"
